title: Bryce BylliGoat • CS 499 ePortfolio
description: batchRename capstone enhancements — Software Design & Engineering • Algorithms & Data Structures • Databases
theme: jekyll-theme-cayman
url: "https://bpagel-snhu.github.io/CS-499-portfolio-bpagel/"
baseurl: "/CS-499-portfolio-bpagel"
